version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  db-migration:
    build: .
    depends_on:
      - "devdb"
      - "backend"
    environment:
      DATABASE_URL: postgres://recipe:RecipePassword@localhost:5432/recipe
    command: bash -c './wait-for-it.sh -h devdb -p 5432 && npx prisma migrate dev'
volumes:
  postgres: